;---------------------------------------------------
; \file  config.inc
; \note  (c) 2025 by Jens Kallup - paule32
;        all rights reserved.
;
; \desc  Create a dBASE MS-Windows 11 64-bit Pro EXE.
;---------------------------------------------------
; Configuration file
;---------------------------------------------------

%define DOS_SHELL 16        ; 1 indicates a console application.
%define DOS_MODE  32        ; set this to 16 for 16 bit DOS or 64 for win32pe+
