:: ---------------------------------------------------
:: \file  showel.bat
:: \note  (c) 2025 by Jens Kallup - paule32
::        all rights reserved.
::
:: \desc  Create a dBASE MS-Windows 11 64-bit Pro EXE.
:: ---------------------------------------------------
:: Nach dem Programmaufruf einfach diese BAT starten.
:: Sie druckt den letzten Errorlevel numerisch aus.
::
:: TODO modify errorlevel deu/enu
:: ---------------------------------------------------
@echo off
if errorlevel 255 goto EL255
if errorlevel 254 goto EL254
if errorlevel 253 goto EL253
if errorlevel 252 goto EL252
if errorlevel 251 goto EL251
if errorlevel 250 goto EL250

if errorlevel 249 goto EL249
if errorlevel 248 goto EL248
if errorlevel 247 goto EL247
if errorlevel 246 goto EL246
if errorlevel 245 goto EL245
if errorlevel 244 goto EL244
if errorlevel 243 goto EL243
if errorlevel 242 goto EL242
if errorlevel 241 goto EL241
if errorlevel 240 goto EL240

if errorlevel 239 goto EL239
if errorlevel 238 goto EL238
if errorlevel 237 goto EL237
if errorlevel 236 goto EL236
if errorlevel 235 goto EL235
if errorlevel 234 goto EL234
if errorlevel 233 goto EL233
if errorlevel 232 goto EL232
if errorlevel 231 goto EL231
if errorlevel 230 goto EL230

if errorlevel 229 goto EL229
if errorlevel 228 goto EL228
if errorlevel 227 goto EL227
if errorlevel 226 goto EL226
if errorlevel 225 goto EL225
if errorlevel 224 goto EL224
if errorlevel 223 goto EL223
if errorlevel 222 goto EL222
if errorlevel 221 goto EL221
if errorlevel 220 goto EL220

if errorlevel 219 goto EL219
if errorlevel 218 goto EL218
if errorlevel 217 goto EL217
if errorlevel 216 goto EL216
if errorlevel 215 goto EL215
if errorlevel 214 goto EL214
if errorlevel 213 goto EL213
if errorlevel 212 goto EL212
if errorlevel 211 goto EL211
if errorlevel 210 goto EL210

if errorlevel 209 goto EL209
if errorlevel 208 goto EL208
if errorlevel 207 goto EL207
if errorlevel 206 goto EL206
if errorlevel 205 goto EL205
if errorlevel 204 goto EL204
if errorlevel 203 goto EL203
if errorlevel 202 goto EL202
if errorlevel 201 goto EL201
if errorlevel 200 goto EL200

if errorlevel 199 goto EL199
if errorlevel 198 goto EL198
if errorlevel 197 goto EL197
if errorlevel 196 goto EL196
if errorlevel 195 goto EL195
if errorlevel 194 goto EL194
if errorlevel 193 goto EL193
if errorlevel 192 goto EL192
if errorlevel 191 goto EL191
if errorlevel 190 goto EL190

if errorlevel 189 goto EL189
if errorlevel 188 goto EL188
if errorlevel 187 goto EL187
if errorlevel 186 goto EL186
if errorlevel 185 goto EL185
if errorlevel 184 goto EL184
if errorlevel 183 goto EL183
if errorlevel 182 goto EL182
if errorlevel 181 goto EL181
if errorlevel 180 goto EL180

if errorlevel 179 goto EL179
if errorlevel 178 goto EL178
if errorlevel 177 goto EL177
if errorlevel 176 goto EL176
if errorlevel 175 goto EL175
if errorlevel 174 goto EL174
if errorlevel 173 goto EL173
if errorlevel 172 goto EL172
if errorlevel 171 goto EL171
if errorlevel 170 goto EL170

if errorlevel 169 goto EL169
if errorlevel 168 goto EL168
if errorlevel 167 goto EL167
if errorlevel 166 goto EL166
if errorlevel 165 goto EL165
if errorlevel 164 goto EL164
if errorlevel 163 goto EL163
if errorlevel 162 goto EL162
if errorlevel 161 goto EL161
if errorlevel 160 goto EL160

if errorlevel 159 goto EL159
if errorlevel 158 goto EL158
if errorlevel 157 goto EL157
if errorlevel 156 goto EL156
if errorlevel 155 goto EL155
if errorlevel 154 goto EL154
if errorlevel 153 goto EL153
if errorlevel 152 goto EL152
if errorlevel 151 goto EL151
if errorlevel 150 goto EL150

if errorlevel 149 goto EL149
if errorlevel 148 goto EL148
if errorlevel 147 goto EL147
if errorlevel 146 goto EL146
if errorlevel 145 goto EL145
if errorlevel 144 goto EL144
if errorlevel 143 goto EL143
if errorlevel 142 goto EL142
if errorlevel 141 goto EL141
if errorlevel 140 goto EL140

if errorlevel 139 goto EL139
if errorlevel 138 goto EL138
if errorlevel 137 goto EL137
if errorlevel 136 goto EL136
if errorlevel 135 goto EL135
if errorlevel 134 goto EL134
if errorlevel 133 goto EL133
if errorlevel 132 goto EL132
if errorlevel 131 goto EL131
if errorlevel 130 goto EL130

if errorlevel 129 goto EL129
if errorlevel 128 goto EL128
if errorlevel 127 goto EL127
if errorlevel 126 goto EL126
if errorlevel 125 goto EL125
if errorlevel 124 goto EL124
if errorlevel 123 goto EL123
if errorlevel 122 goto EL122
if errorlevel 121 goto EL121
if errorlevel 120 goto EL120

if errorlevel 119 goto EL119
if errorlevel 118 goto EL118
if errorlevel 117 goto EL117
if errorlevel 116 goto EL116
if errorlevel 115 goto EL115
if errorlevel 114 goto EL114
if errorlevel 113 goto EL113
if errorlevel 112 goto EL112
if errorlevel 111 goto EL111
if errorlevel 110 goto EL110

if errorlevel 109 goto EL109
if errorlevel 108 goto EL108
if errorlevel 107 goto EL107
if errorlevel 106 goto EL106
if errorlevel 105 goto EL105
if errorlevel 104 goto EL104
if errorlevel 103 goto EL103
if errorlevel 102 goto EL102
if errorlevel 101 goto EL101
if errorlevel 100 goto EL100

if errorlevel 99 goto EL99
if errorlevel 98 goto EL98
if errorlevel 97 goto EL97
if errorlevel 96 goto EL96
if errorlevel 95 goto EL95
if errorlevel 94 goto EL94
if errorlevel 93 goto EL93
if errorlevel 92 goto EL92
if errorlevel 91 goto EL91
if errorlevel 90 goto EL90

if errorlevel 89 goto EL89
if errorlevel 88 goto EL88
if errorlevel 87 goto EL87
if errorlevel 86 goto EL86
if errorlevel 85 goto EL85
if errorlevel 84 goto EL84
if errorlevel 83 goto EL83
if errorlevel 82 goto EL82
if errorlevel 81 goto EL81
if errorlevel 80 goto EL80

if errorlevel 79 goto EL79
if errorlevel 78 goto EL78
if errorlevel 77 goto EL77
if errorlevel 76 goto EL76
if errorlevel 75 goto EL75
if errorlevel 74 goto EL74
if errorlevel 73 goto EL73
if errorlevel 72 goto EL72
if errorlevel 71 goto EL71
if errorlevel 70 goto EL70

if errorlevel 69 goto EL69
if errorlevel 68 goto EL68
if errorlevel 67 goto EL67
if errorlevel 66 goto EL66
if errorlevel 65 goto EL65
if errorlevel 64 goto EL64
if errorlevel 63 goto EL63
if errorlevel 62 goto EL62
if errorlevel 61 goto EL61
if errorlevel 60 goto EL60

if errorlevel 59 goto EL59
if errorlevel 58 goto EL58
if errorlevel 57 goto EL57
if errorlevel 56 goto EL56
if errorlevel 55 goto EL55
if errorlevel 54 goto EL54
if errorlevel 53 goto EL53
if errorlevel 52 goto EL52
if errorlevel 51 goto EL51
if errorlevel 50 goto EL50

if errorlevel 49 goto EL49
if errorlevel 48 goto EL48
if errorlevel 47 goto EL47
if errorlevel 46 goto EL46
if errorlevel 45 goto EL45
if errorlevel 44 goto EL44
if errorlevel 43 goto EL43
if errorlevel 42 goto EL42
if errorlevel 41 goto EL41
if errorlevel 40 goto EL40

if errorlevel 39 goto EL39
if errorlevel 38 goto EL38
if errorlevel 37 goto EL37
if errorlevel 36 goto EL36
if errorlevel 35 goto EL35
if errorlevel 34 goto EL34
if errorlevel 33 goto EL33
if errorlevel 32 goto EL32
if errorlevel 31 goto EL31
if errorlevel 30 goto EL30

if errorlevel 29 goto EL29
if errorlevel 28 goto EL28
if errorlevel 27 goto EL27
if errorlevel 26 goto EL26
if errorlevel 25 goto EL25
if errorlevel 24 goto EL24
if errorlevel 23 goto EL23
if errorlevel 22 goto EL22
if errorlevel 21 goto EL21
if errorlevel 20 goto EL20

if errorlevel 19 goto EL19
if errorlevel 18 goto EL18
if errorlevel 17 goto EL17
if errorlevel 16 goto EL16
if errorlevel 15 goto EL15
if errorlevel 14 goto EL14
if errorlevel 13 goto EL13
if errorlevel 12 goto EL12
if errorlevel 11 goto EL11
if errorlevel 10 goto EL10

if errorlevel 9 goto EL9
if errorlevel 8 goto EL8
if errorlevel 7 goto EL7
if errorlevel 6 goto EL6
if errorlevel 5 goto EL5
if errorlevel 4 goto EL4
if errorlevel 3 goto EL3
if errorlevel 2 goto EL2
if errorlevel 1 goto EL1
goto EL0

:EL255
getlang.com
if errorlevel 49 goto EL255DEU
goto EL255ENU
:EL255DEU
echo ERRORLEVEL=255
goto DONE
:EL255ENU
echo ERRORLEVEL=255
goto DONE

:EL254
getlang.com
if errorlevel 49 goto EL254DEU
goto EL254ENU
:EL254DEU
echo ERRORLEVEL=254
goto DONE
:EL254ENU
echo ERRORLEVEL=254
goto DONE

:EL253
getlang.com
if errorlevel 49 goto EL253DEU
goto EL253ENU
:EL253DEU
echo ERRORLEVEL=253
goto DONE
:EL253ENU
echo ERRORLEVEL=253
goto DONE

:EL252
getlang.com
if errorlevel 49 goto EL252DEU
goto EL252ENU
:EL252DEU
echo ERRORLEVEL=252
goto DONE
:EL252ENU
echo ERRORLEVEL=252
goto DONE

:EL251
getlang.com
if errorlevel 49 goto EL251DEU
goto EL251ENU
:EL251DEU
echo ERRORLEVEL=251
goto DONE
:EL251ENU
echo ERRORLEVEL=251
goto DONE

:EL250
getlang.com
if errorlevel 49 goto EL250DEU
goto EL250ENU
:EL250DEU
echo ERRORLEVEL=250
goto DONE
:EL250ENU
echo ERRORLEVEL=250
goto DONE

:EL249
getlang.com
if errorlevel 49 goto EL249DEU
goto EL249ENU
:EL249DEU
echo ERRORLEVEL=249
goto DONE
:EL249ENU
echo ERRORLEVEL=249
goto DONE

:EL248
getlang.com
if errorlevel 49 goto EL248DEU
goto EL248ENU
:EL248DEU
echo ERRORLEVEL=248
goto DONE
:EL248ENU
echo ERRORLEVEL=248
goto DONE

:EL247
getlang.com
if errorlevel 49 goto EL247DEU
goto EL247ENU
:EL247DEU
echo ERRORLEVEL=247
goto DONE
:EL247ENU
echo ERRORLEVEL=247
goto DONE

:EL246
getlang.com
if errorlevel 49 goto EL246DEU
goto EL246ENU
:EL246DEU
echo ERRORLEVEL=246
goto DONE
:EL246ENU
echo ERRORLEVEL=246
goto DONE

:EL245
getlang.com
if errorlevel 49 goto EL245DEU
goto EL245ENU
:EL245DEU
echo ERRORLEVEL=245
goto DONE
:EL245ENU
echo ERRORLEVEL=245
goto DONE

:EL244
getlang.com
if errorlevel 49 goto EL244DEU
goto EL244ENU
:EL244DEU
echo ERRORLEVEL=244
goto DONE
:EL244ENU
echo ERRORLEVEL=244
goto DONE

:EL243
getlang.com
if errorlevel 49 goto EL243DEU
goto EL243ENU
:EL243DEU
echo ERRORLEVEL=243
goto DONE
:EL243ENU
echo ERRORLEVEL=243
goto DONE

:EL242
getlang.com
if errorlevel 49 goto EL242DEU
goto EL242ENU
:EL242DEU
echo ERRORLEVEL=242
goto DONE
:EL242ENU
echo ERRORLEVEL=242
goto DONE

:EL241
getlang.com
if errorlevel 49 goto EL241DEU
goto EL241ENU
:EL241DEU
echo ERRORLEVEL=241
goto DONE
:EL241ENU
echo ERRORLEVEL=241
goto DONE

:EL240
getlang.com
if errorlevel 49 goto EL240DEU
goto EL240ENU
:EL240DEU
echo ERRORLEVEL=240
goto DONE
:EL240ENU
echo ERRORLEVEL=240
goto DONE

:EL239
getlang.com
if errorlevel 49 goto EL239DEU
goto EL239ENU
:EL239DEU
echo ERRORLEVEL=239
goto DONE
:EL239ENU
echo ERRORLEVEL=239
goto DONE

:EL238
getlang.com
if errorlevel 49 goto EL38DEU
goto EL238ENU
:EL238DEU
echo ERRORLEVEL=238
goto DONE
:EL238ENU
echo ERRORLEVEL=238
goto DONE

:EL237
getlang.com
if errorlevel 49 goto EL237DEU
goto EL237ENU
:EL237DEU
echo ERRORLEVEL=237
goto DONE
:EL237ENU
echo ERRORLEVEL=237
goto DONE

:EL236
getlang.com
if errorlevel 49 goto EL236DEU
goto EL236ENU
:EL236DEU
echo ERRORLEVEL=236
goto DONE
:EL236ENU
echo ERRORLEVEL=236
goto DONE

:EL235
getlang.com
if errorlevel 49 goto EL235DEU
goto EL235ENU
:EL235DEU
echo ERRORLEVEL=235
goto DONE
:EL235ENU
echo ERRORLEVEL=235
goto DONE

:EL234
getlang.com
if errorlevel 49 goto EL234DEU
goto EL234ENU
:EL234DEU
echo ERRORLEVEL=234
goto DONE
:EL234ENU
echo ERRORLEVEL=234
goto DONE

:EL233
getlang.com
if errorlevel 49 goto EL233DEU
goto EL233ENU
:EL233DEU
echo ERRORLEVEL=233
goto DONE
:EL233ENU
echo ERRORLEVEL=233
goto DONE

:EL232
getlang.com
if errorlevel 49 goto EL2321DEU
goto EL232ENU
:EL232DEU
echo ERRORLEVEL=232
goto DONE
:EL232ENU
echo ERRORLEVEL=232
goto DONE

:EL231
getlang.com
if errorlevel 49 goto EL231DEU
goto EL231ENU
:EL231DEU
echo ERRORLEVEL=231
goto DONE
:EL231ENU
echo ERRORLEVEL=231
goto DONE

:EL230
getlang.com
if errorlevel 49 goto EL230DEU
goto EL230ENU
:EL230DEU
echo ERRORLEVEL=230
goto DONE
:EL230ENU
echo ERRORLEVEL=230
goto DONE

:EL229
getlang.com
if errorlevel 49 goto EL229DEU
goto EL229ENU
:EL229DEU
echo ERRORLEVEL=229
goto DONE
:EL229ENU
echo ERRORLEVEL=229
goto DONE

:EL228
getlang.com
if errorlevel 49 goto EL228DEU
goto EL228ENU
:EL228DEU
echo ERRORLEVEL=228
goto DONE
:EL228ENU
echo ERRORLEVEL=228
goto DONE

:EL227
getlang.com
if errorlevel 49 goto EL227DEU
goto EL227ENU
:EL227DEU
echo ERRORLEVEL=227
goto DONE
:EL227ENU
echo ERRORLEVEL=227
goto DONE

:EL226
getlang.com
if errorlevel 49 goto EL226DEU
goto EL226ENU
:EL226DEU
echo ERRORLEVEL=226
goto DONE
:EL226ENU
echo ERRORLEVEL=226
goto DONE

:EL225
getlang.com
if errorlevel 49 goto EL225DEU
goto EL225ENU
:EL225DEU
echo ERRORLEVEL=225
goto DONE
:EL225ENU
echo ERRORLEVEL=225
goto DONE

:EL224
getlang.com
if errorlevel 49 goto EL224DEU
goto EL224ENU
:EL224DEU
echo ERRORLEVEL=224
goto DONE
:EL224ENU
echo ERRORLEVEL=224
goto DONE

:EL223
getlang.com
if errorlevel 49 goto EL223DEU
goto EL223ENU
:EL223DEU
echo ERRORLEVEL=223
goto DONE
:EL223ENU
echo ERRORLEVEL=223
goto DONE

:EL222
getlang.com
if errorlevel 49 goto EL222DEU
goto EL222ENU
:EL222DEU
echo ERRORLEVEL=222
goto DONE
:EL222ENU
echo ERRORLEVEL=222
goto DONE

:EL221
getlang.com
if errorlevel 49 goto EL221DEU
goto EL221ENU
:EL221DEU
echo ERRORLEVEL=221
goto DONE
:EL221ENU
echo ERRORLEVEL=221
goto DONE

:EL220
getlang.com
if errorlevel 49 goto EL220DEU
goto EL220ENU
:EL220DEU
echo ERRORLEVEL=220
goto DONE
:EL220ENU
echo ERRORLEVEL=220
goto DONE

:EL219
getlang.com
if errorlevel 49 goto EL219DEU
goto EL219ENU
:EL219DEU
echo ERRORLEVEL=219
goto DONE
:EL219ENU
echo ERRORLEVEL=219
goto DONE

:EL218
getlang.com
if errorlevel 49 goto EL218DEU
goto EL218ENU
:EL218DEU
echo ERRORLEVEL=218
goto DONE
:EL218ENU
echo ERRORLEVEL=218
goto DONE

:EL217
getlang.com
if errorlevel 49 goto EL217DEU
goto EL217ENU
:EL217DEU
echo ERRORLEVEL=217
goto DONE
:EL217ENU
echo ERRORLEVEL=217
goto DONE

:EL216
getlang.com
if errorlevel 49 goto EL216DEU
goto EL216ENU
:EL216DEU
echo ERRORLEVEL=216
goto DONE
:EL216ENU
echo ERRORLEVEL=216
goto DONE

:EL215
getlang.com
if errorlevel 49 goto EL215DEU
goto EL215ENU
:EL215DEU
echo ERRORLEVEL=215
goto DONE
:EL215ENU
echo ERRORLEVEL=215
goto DONE

:EL214
getlang.com
if errorlevel 49 goto EL214DEU
goto EL214ENU
:EL214DEU
echo ERRORLEVEL=214
goto DONE
:EL214ENU
echo ERRORLEVEL=214
goto DONE

:EL213
getlang.com
if errorlevel 49 goto EL213DEU
goto EL213ENU
:EL213DEU
echo ERRORLEVEL=213
goto DONE
:EL213ENU
echo ERRORLEVEL=213
goto DONE

:EL212
getlang.com
if errorlevel 49 goto EL212DEU
goto EL1ENU
:EL212DEU
echo ERRORLEVEL=212
goto DONE
:EL212ENU
echo ERRORLEVEL=212
goto DONE

:EL211
getlang.com
if errorlevel 49 goto EL211DEU
goto EL211ENU
:EL211DEU
echo ERRORLEVEL=211
goto DONE
:EL211ENU
echo ERRORLEVEL=211
goto DONE

:EL210
getlang.com
if errorlevel 49 goto EL210DEU
goto EL210ENU
:EL210DEU
echo ERRORLEVEL=210
goto DONE
:EL210ENU
echo ERRORLEVEL=210
goto DONE

:EL209
getlang.com
if errorlevel 49 goto EL209DEU
goto EL209ENU
:EL209DEU
echo ERRORLEVEL=209
goto DONE
:EL209ENU
echo ERRORLEVEL=209
goto DONE

:EL208
getlang.com
if errorlevel 49 goto EL208DEU
goto EL208ENU
:EL208DEU
echo ERRORLEVEL=208
goto DONE
:EL208ENU
echo ERRORLEVEL=208
goto DONE

:EL207
getlang.com
if errorlevel 49 goto EL207DEU
goto EL207ENU
:EL207DEU
echo ERRORLEVEL=207
goto DONE
:EL207ENU
echo ERRORLEVEL=207
goto DONE

:EL206
getlang.com
if errorlevel 49 goto EL206DEU
goto EL206ENU
:EL206DEU
echo ERRORLEVEL=206
goto DONE
:EL206ENU
echo ERRORLEVEL=206
goto DONE

:EL205
getlang.com
if errorlevel 49 goto EL205DEU
goto EL205ENU
:EL205DEU
echo ERRORLEVEL=205
goto DONE
:EL205ENU
echo ERRORLEVEL=205
goto DONE

:EL204
getlang.com
if errorlevel 49 goto EL204DEU
goto EL204ENU
:EL204DEU
echo ERRORLEVEL=204
goto DONE
:EL204ENU
echo ERRORLEVEL=204
goto DONE

:EL203
getlang.com
if errorlevel 49 goto EL203DEU
goto EL203ENU
:EL203DEU
echo ERRORLEVEL=203
goto DONE
:EL203ENU
echo ERRORLEVEL=203
goto DONE

:EL202
getlang.com
if errorlevel 49 goto EL202DEU
goto EL202ENU
:EL202DEU
echo ERRORLEVEL=202
goto DONE
:EL202ENU
echo ERRORLEVEL=202
goto DONE

:EL201
getlang.com
if errorlevel 49 goto EL201DEU
goto EL201ENU
:EL201DEU
echo ERRORLEVEL=201
goto DONE
:EL201ENU
echo ERRORLEVEL=201
goto DONE

:EL200
getlang.com
if errorlevel 49 goto EL200DEU
goto EL200ENU
:EL200DEU
echo ERRORLEVEL=200
goto DONE
:EL200ENU
echo ERRORLEVEL=200
goto DONE

:EL199
getlang.com
if errorlevel 49 goto EL199DEU
goto EL199ENU
:EL199DEU
echo ERRORLEVEL=199
goto DONE
:EL199ENU
echo ERRORLEVEL=199
goto DONE

:EL198
getlang.com
if errorlevel 49 goto EL198DEU
goto EL198ENU
:EL198DEU
echo ERRORLEVEL=198
goto DONE
:EL198ENU
echo ERRORLEVEL=198
goto DONE

:EL197
getlang.com
if errorlevel 49 goto EL197DEU
goto EL197ENU
:EL197DEU
echo ERRORLEVEL=197
goto DONE
:EL197ENU
echo ERRORLEVEL=197
goto DONE

:EL196
getlang.com
if errorlevel 49 goto EL196DEU
goto EL196ENU
:EL196DEU
echo ERRORLEVEL=196
goto DONE
:EL196ENU
echo ERRORLEVEL=196
goto DONE

:EL195
getlang.com
if errorlevel 49 goto EL195DEU
goto EL1ENU
:EL195DEU
echo ERRORLEVEL=195
goto DONE
:EL195ENU
echo ERRORLEVEL=195
goto DONE

:EL194
getlang.com
if errorlevel 49 goto EL194DEU
goto EL194ENU
:EL194DEU
echo ERRORLEVEL=194
goto DONE
:EL194ENU
echo ERRORLEVEL=194
goto DONE

:EL193
getlang.com
if errorlevel 49 goto EL193DEU
goto EL193ENU
:EL193DEU
echo ERRORLEVEL=193
goto DONE
:EL193ENU
echo ERRORLEVEL=193
goto DONE

:EL192
getlang.com
if errorlevel 49 goto EL192DEU
goto EL192ENU
:EL192DEU
echo ERRORLEVEL=192
goto DONE
:EL192ENU
echo ERRORLEVEL=192
goto DONE

:EL191
getlang.com
if errorlevel 49 goto EL191DEU
goto EL191ENU
:EL191DEU
echo ERRORLEVEL=191
goto DONE
:EL191ENU
echo ERRORLEVEL=191
goto DONE

:EL190
getlang.com
if errorlevel 49 goto EL190DEU
goto EL190ENU
:EL190DEU
echo ERRORLEVEL=190
goto DONE
:EL190ENU
echo ERRORLEVEL=190
goto DONE

:EL189
getlang.com
if errorlevel 49 goto EL189DEU
goto EL189ENU
:EL189DEU
echo ERRORLEVEL=189
goto DONE
:EL189ENU
echo ERRORLEVEL=189
goto DONE

:EL188
getlang.com
if errorlevel 49 goto EL188DEU
goto EL188ENU
:EL188DEU
echo ERRORLEVEL=188
goto DONE
:EL188ENU
echo ERRORLEVEL=188
goto DONE

:EL187
getlang.com
if errorlevel 49 goto EL187DEU
goto EL187ENU
:EL187DEU
echo ERRORLEVEL=187
goto DONE
:EL187ENU
echo ERRORLEVEL=187
goto DONE

:EL186
getlang.com
if errorlevel 49 goto EL186DEU
goto EL186ENU
:EL186DEU
echo ERRORLEVEL=186
goto DONE
:EL186ENU
echo ERRORLEVEL=186
goto DONE

:EL185
getlang.com
if errorlevel 49 goto EL185DEU
goto EL185ENU
:EL185DEU
echo ERRORLEVEL=185
goto DONE
:EL185ENU
echo ERRORLEVEL=185
goto DONE

:EL184
getlang.com
if errorlevel 49 goto EL184DEU
goto EL184ENU
:EL184DEU
echo ERRORLEVEL=184
goto DONE
:EL184ENU
echo ERRORLEVEL=184
goto DONE

:EL183
getlang.com
if errorlevel 49 goto EL183DEU
goto EL183ENU
:EL183DEU
echo ERRORLEVEL=183
goto DONE
:EL183ENU
echo ERRORLEVEL=183
goto DONE

:EL182
getlang.com
if errorlevel 49 goto EL182DEU
goto EL182ENU
:EL182DEU
echo ERRORLEVEL=182
goto DONE
:EL182ENU
echo ERRORLEVEL=182
goto DONE

:EL181
getlang.com
if errorlevel 49 goto EL181DEU
goto EL181ENU
:EL181DEU
echo ERRORLEVEL=181
goto DONE
:EL181ENU
echo ERRORLEVEL=181
goto DONE

:EL180
getlang.com
if errorlevel 49 goto EL180DEU
goto EL180ENU
:EL180DEU
echo ERRORLEVEL=180
goto DONE
:EL180ENU
echo ERRORLEVEL=180
goto DONE

:EL179
getlang.com
if errorlevel 49 goto EL179DEU
goto EL179ENU
:EL179DEU
echo ERRORLEVEL=179
goto DONE
:EL179ENU
echo ERRORLEVEL=179
goto DONE

:EL178
getlang.com
if errorlevel 49 goto EL178DEU
goto EL178ENU
:EL178DEU
echo ERRORLEVEL=178
goto DONE
:EL178ENU
echo ERRORLEVEL=178
goto DONE

:EL177
getlang.com
if errorlevel 49 goto EL177DEU
goto EL177ENU
:EL177DEU
echo ERRORLEVEL=177
goto DONE
:EL177ENU
echo ERRORLEVEL=177
goto DONE

:EL176
getlang.com
if errorlevel 49 goto EL176DEU
goto EL176ENU
:EL176DEU
echo ERRORLEVEL=176
goto DONE
:EL176ENU
echo ERRORLEVEL=176
goto DONE

:EL175
getlang.com
if errorlevel 49 goto EL175DEU
goto EL175ENU
:EL175DEU
echo ERRORLEVEL=175
goto DONE
:EL175ENU
echo ERRORLEVEL=175
goto DONE

:EL174
getlang.com
if errorlevel 49 goto EL174DEU
goto EL174ENU
:EL174DEU
echo ERRORLEVEL=174
goto DONE
:EL174ENU
echo ERRORLEVEL=174
goto DONE

:EL173
getlang.com
if errorlevel 49 goto EL173DEU
goto EL173ENU
:EL173DEU
echo ERRORLEVEL=173
goto DONE
:EL173ENU
echo ERRORLEVEL=173
goto DONE

:EL172
getlang.com
if errorlevel 49 goto EL172DEU
goto EL172ENU
:EL172DEU
echo ERRORLEVEL=172
goto DONE
:EL172ENU
echo ERRORLEVEL=172
goto DONE

:EL171
getlang.com
if errorlevel 49 goto EL171DEU
goto EL171ENU
:EL171DEU
echo ERRORLEVEL=171
goto DONE
:EL171ENU
echo ERRORLEVEL=171
goto DONE

:EL170
getlang.com
if errorlevel 49 goto EL170DEU
goto EL170ENU
:EL170DEU
echo ERRORLEVEL=170
goto DONE
:EL170ENU
echo ERRORLEVEL=170
goto DONE

:EL169
getlang.com
if errorlevel 49 goto EL169DEU
goto EL169ENU
:EL169DEU
echo ERRORLEVEL=169
goto DONE
:EL169ENU
echo ERRORLEVEL=169
goto DONE

:EL168
getlang.com
if errorlevel 49 goto EL168DEU
goto EL168ENU
:EL168DEU
echo ERRORLEVEL=168
goto DONE
:EL168ENU
echo ERRORLEVEL=168
goto DONE

:EL167
getlang.com
if errorlevel 49 goto EL167DEU
goto EL167ENU
:EL167DEU
echo ERRORLEVEL=167
goto DONE
:EL167ENU
echo ERRORLEVEL=167
goto DONE

:EL166
getlang.com
if errorlevel 49 goto EL166DEU
goto EL166ENU
:EL166DEU
echo ERRORLEVEL=166
goto DONE
:EL166ENU
echo ERRORLEVEL=166
goto DONE

:EL165
getlang.com
if errorlevel 49 goto EL165DEU
goto EL165ENU
:EL165DEU
echo ERRORLEVEL=165
goto DONE
:EL165ENU
echo ERRORLEVEL=166
goto DONE

:EL164
getlang.com
if errorlevel 49 goto EL164DEU
goto EL164ENU
:EL164DEU
echo ERRORLEVEL=164
goto DONE
:EL164ENU
echo ERRORLEVEL=164
goto DONE

:EL163
getlang.com
if errorlevel 49 goto EL163DEU
goto EL163ENU
:EL163DEU
echo ERRORLEVEL=163
goto DONE
:EL163ENU
echo ERRORLEVEL=163
goto DONE

:EL162
getlang.com
if errorlevel 49 goto EL162DEU
goto EL162ENU
:EL162DEU
echo ERRORLEVEL=162
goto DONE
:EL162ENU
echo ERRORLEVEL=162
goto DONE

:EL161
getlang.com
if errorlevel 49 goto EL161DEU
goto EL161ENU
:EL161DEU
echo ERRORLEVEL=161
goto DONE
:EL161ENU
echo ERRORLEVEL=161
goto DONE

:EL160
getlang.com
if errorlevel 49 goto EL160DEU
goto EL160ENU
:EL160DEU
echo ERRORLEVEL=160
goto DONE
:EL169ENU
echo ERRORLEVEL=160
goto DONE

:EL159
getlang.com
if errorlevel 49 goto EL159DEU
goto EL159ENU
:EL159DEU
echo ERRORLEVEL=159
goto DONE
:EL159ENU
echo ERRORLEVEL=159
goto DONE

:EL158
getlang.com
if errorlevel 49 goto EL158DEU
goto EL158ENU
:EL158DEU
echo ERRORLEVEL=158
goto DONE
:EL158ENU
echo ERRORLEVEL=158
goto DONE

:EL157
getlang.com
if errorlevel 49 goto EL157DEU
goto EL157ENU
:EL157DEU
echo ERRORLEVEL=157
goto DONE
:EL157ENU
echo ERRORLEVEL=157
goto DONE

:EL156
getlang.com
if errorlevel 49 goto EL156DEU
goto EL156ENU
:EL156DEU
echo ERRORLEVEL=156
goto DONE
:EL156ENU
echo ERRORLEVEL=156
goto DONE

:EL155
getlang.com
if errorlevel 49 goto EL155DEU
goto EL155ENU
:EL155DEU
echo ERRORLEVEL=155
goto DONE
:EL155ENU
echo ERRORLEVEL=155
goto DONE

:EL154
getlang.com
if errorlevel 49 goto EL154DEU
goto EL154ENU
:EL154DEU
echo ERRORLEVEL=154
goto DONE
:EL154ENU
echo ERRORLEVEL=154
goto DONE

:EL153
getlang.com
if errorlevel 49 goto EL153DEU
goto EL153ENU
:EL153DEU
echo ERRORLEVEL=153
goto DONE
:EL153ENU
echo ERRORLEVEL=153
goto DONE

:EL152
getlang.com
if errorlevel 49 goto EL152DEU
goto EL152ENU
:EL152DEU
echo ERRORLEVEL=152
goto DONE
:EL152ENU
echo ERRORLEVEL=152
goto DONE

:EL151
getlang.com
if errorlevel 49 goto EL151DEU
goto EL151ENU
:EL151DEU
echo ERRORLEVEL=151
goto DONE
:EL151ENU
echo ERRORLEVEL=151
goto DONE

:EL150
getlang.com
if errorlevel 49 goto EL150DEU
goto EL150ENU
:EL150DEU
echo ERRORLEVEL=150
goto DONE
:EL150ENU
echo ERRORLEVEL=150
goto DONE

:EL149
getlang.com
if errorlevel 49 goto EL149DEU
goto EL149ENU
:EL149DEU
echo ERRORLEVEL=149
goto DONE
:EL149ENU
echo ERRORLEVEL=149
goto DONE

:EL148
getlang.com
if errorlevel 49 goto EL148DEU
goto EL148ENU
:EL148DEU
echo ERRORLEVEL=148
goto DONE
:EL148ENU
echo ERRORLEVEL=148
goto DONE

:EL147
getlang.com
if errorlevel 49 goto EL147DEU
goto EL147ENU
:EL147DEU
echo ERRORLEVEL=147
goto DONE
:EL147ENU
echo ERRORLEVEL=147
goto DONE

:EL146
getlang.com
if errorlevel 49 goto EL146DEU
goto EL146ENU
:EL146DEU
echo ERRORLEVEL=146
goto DONE
:EL146ENU
echo ERRORLEVEL=146
goto DONE

:EL145
getlang.com
if errorlevel 49 goto EL145DEU
goto EL145ENU
:EL145DEU
echo ERRORLEVEL=145
goto DONE
:EL145ENU
echo ERRORLEVEL=145
goto DONE

:EL144
getlang.com
if errorlevel 49 goto EL144DEU
goto EL144ENU
:EL144DEU
echo ERRORLEVEL=144
goto DONE
:EL144ENU
echo ERRORLEVEL=144
goto DONE

:EL143
getlang.com
if errorlevel 49 goto EL143DEU
goto EL143ENU
:EL143DEU
echo ERRORLEVEL=143
goto DONE
:EL143ENU
echo ERRORLEVEL=143
goto DONE

:EL142
getlang.com
if errorlevel 49 goto EL142DEU
goto EL142ENU
:EL142DEU
echo ERRORLEVEL=142
goto DONE
:EL142ENU
echo ERRORLEVEL=142
goto DONE

:EL141
getlang.com
if errorlevel 49 goto EL141DEU
goto EL141ENU
:EL141DEU
echo ERRORLEVEL=141
goto DONE
:EL141ENU
echo ERRORLEVEL=141
goto DONE

:EL140
getlang.com
if errorlevel 49 goto EL140DEU
goto EL140ENU
:EL140DEU
echo ERRORLEVEL=140
goto DONE
:EL140ENU
echo ERRORLEVEL=140
goto DONE

:EL139
getlang.com
if errorlevel 49 goto EL139DEU
goto EL139ENU
:EL139DEU
echo ERRORLEVEL=139
goto DONE
:EL139ENU
echo ERRORLEVEL=139
goto DONE

:EL138
getlang.com
if errorlevel 49 goto EL138DEU
goto EL138ENU
:EL138DEU
echo ERRORLEVEL=138
goto DONE
:EL138ENU
echo ERRORLEVEL=138
goto DONE

:EL137
getlang.com
if errorlevel 49 goto EL137DEU
goto EL137ENU
:EL137DEU
echo ERRORLEVEL=137
goto DONE
:EL137ENU
echo ERRORLEVEL=137
goto DONE

:EL136
getlang.com
if errorlevel 49 goto EL136DEU
goto EL136ENU
:EL136DEU
echo ERRORLEVEL=136
goto DONE
:EL136ENU
echo ERRORLEVEL=136
goto DONE

:EL135
getlang.com
if errorlevel 49 goto EL135DEU
goto EL135ENU
:EL135DEU
echo ERRORLEVEL=135
goto DONE
:EL135ENU
echo ERRORLEVEL=135
goto DONE

:EL134
getlang.com
if errorlevel 49 goto EL134DEU
goto EL134ENU
:EL134DEU
echo ERRORLEVEL=134
goto DONE
:EL134ENU
echo ERRORLEVEL=134
goto DONE

:EL133
getlang.com
if errorlevel 49 goto EL133DEU
goto EL133ENU
:EL133DEU
echo ERRORLEVEL=133
goto DONE
:EL133ENU
echo ERRORLEVEL=133
goto DONE

:EL132
getlang.com
if errorlevel 49 goto EL132DEU
goto EL132ENU
:EL132DEU
echo ERRORLEVEL=132
goto DONE
:EL132ENU
echo ERRORLEVEL=132
goto DONE

:EL131
getlang.com
if errorlevel 49 goto EL131DEU
goto EL131ENU
:EL131DEU
echo ERRORLEVEL=131
goto DONE
:EL131ENU
echo ERRORLEVEL=131
goto DONE

:EL130
getlang.com
if errorlevel 49 goto EL130DEU
goto EL130ENU
:EL130DEU
echo ERRORLEVEL=130
goto DONE
:EL130ENU
echo ERRORLEVEL=130
goto DONE

:EL129
getlang.com
if errorlevel 49 goto EL129DEU
goto EL129ENU
:EL129DEU
echo ERRORLEVEL=129
goto DONE
:EL129ENU
echo ERRORLEVEL=129
goto DONE

:EL128
getlang.com
if errorlevel 49 goto EL128DEU
goto EL128ENU
:EL128DEU
echo ERRORLEVEL=128
goto DONE
:EL128ENU
echo ERRORLEVEL=128
goto DONE

:EL127
getlang.com
if errorlevel 49 goto EL127DEU
goto EL127ENU
:EL127DEU
echo ERRORLEVEL=127
goto DONE
:EL127ENU
echo ERRORLEVEL=127
goto DONE

:EL126
getlang.com
if errorlevel 49 goto EL126DEU
goto EL126ENU
:EL126DEU
echo ERRORLEVEL=126
goto DONE
:EL126ENU
echo ERRORLEVEL=126
goto DONE

:EL125
getlang.com
if errorlevel 49 goto EL125DEU
goto EL125ENU
:EL125DEU
echo ERRORLEVEL=125
goto DONE
:EL125ENU
echo ERRORLEVEL=125
goto DONE

:EL124
getlang.com
if errorlevel 49 goto EL124DEU
goto EL124ENU
:EL124DEU
echo ERRORLEVEL=124
goto DONE
:EL124ENU
echo ERRORLEVEL=124
goto DONE

:EL123
getlang.com
if errorlevel 49 goto EL123DEU
goto EL123ENU
:EL123DEU
echo ERRORLEVEL=123
goto DONE
:EL123ENU
echo ERRORLEVEL=123
goto DONE

:EL122
getlang.com
if errorlevel 49 goto EL122DEU
goto EL122ENU
:EL122DEU
echo ERRORLEVEL=122
goto DONE
:EL122ENU
echo ERRORLEVEL=122
goto DONE

:EL121
getlang.com
if errorlevel 49 goto EL121DEU
goto EL121ENU
:EL121DEU
echo ERRORLEVEL=121
goto DONE
:EL121ENU
echo ERRORLEVEL=121
goto DONE

:EL120
getlang.com
if errorlevel 49 goto EL120DEU
goto EL120ENU
:EL120DEU
echo ERRORLEVEL=120
goto DONE
:EL120ENU
echo ERRORLEVEL=120
goto DONE

:EL119
getlang.com
if errorlevel 49 goto EL119DEU
goto EL119ENU
:EL119DEU
echo ERRORLEVEL=119
goto DONE
:EL119ENU
echo ERRORLEVEL=119
goto DONE

:EL118
getlang.com
if errorlevel 49 goto EL118DEU
goto EL118ENU
:EL118DEU
echo ERRORLEVEL=118
goto DONE
:EL118ENU
echo ERRORLEVEL=118
goto DONE

:EL117
getlang.com
if errorlevel 49 goto EL117DEU
goto EL117ENU
:EL117DEU
echo ERRORLEVEL=117
goto DONE
:EL117ENU
echo ERRORLEVEL=117
goto DONE

:EL116
getlang.com
if errorlevel 49 goto EL116DEU
goto EL116ENU
:EL116DEU
echo ERRORLEVEL=116
goto DONE
:EL116ENU
echo ERRORLEVEL=116
goto DONE

:EL115
getlang.com
if errorlevel 49 goto EL115DEU
goto EL115ENU
:EL115DEU
echo ERRORLEVEL=115
goto DONE
:EL115ENU
echo ERRORLEVEL=115
goto DONE

:EL114
getlang.com
if errorlevel 49 goto EL114DEU
goto EL114ENU
:EL114DEU
echo ERRORLEVEL=114
goto DONE
:EL114ENU
echo ERRORLEVEL=114
goto DONE

:EL113
getlang.com
if errorlevel 49 goto EL113DEU
goto EL113ENU
:EL113DEU
echo ERRORLEVEL=113
goto DONE
:EL113ENU
echo ERRORLEVEL=113
goto DONE

:EL112
getlang.com
if errorlevel 49 goto EL112DEU
goto EL112ENU
:EL112DEU
echo ERRORLEVEL=112
goto DONE
:EL112ENU
echo ERRORLEVEL=112
goto DONE

:EL111
getlang.com
if errorlevel 49 goto EL111DEU
goto EL111ENU
:EL111DEU
echo ERRORLEVEL=111
goto DONE
:EL111ENU
echo ERRORLEVEL=111
goto DONE

:EL110
getlang.com
if errorlevel 49 goto EL110DEU
goto EL110ENU
:EL110DEU
echo ERRORLEVEL=110
goto DONE
:EL110ENU
echo ERRORLEVEL=110
goto DONE

:EL109
getlang.com
if errorlevel 49 goto EL109DEU
goto EL109ENU
:EL109DEU
echo ERRORLEVEL=109
goto DONE
:EL109ENU
echo ERRORLEVEL=109
goto DONE

:EL108
getlang.com
if errorlevel 49 goto EL108DEU
goto EL108ENU
:EL108DEU
echo ERRORLEVEL=108
goto DONE
:EL108ENU
echo ERRORLEVEL=108
goto DONE

:EL107
getlang.com
if errorlevel 49 goto EL107DEU
goto EL107ENU
:EL107DEU
echo ERRORLEVEL=107
goto DONE
:EL107ENU
echo ERRORLEVEL=107
goto DONE

:EL106
getlang.com
if errorlevel 49 goto EL106DEU
goto EL106ENU
:EL106DEU
echo ERRORLEVEL=106
goto DONE
:EL106ENU
echo ERRORLEVEL=106
goto DONE

:EL105
getlang.com
if errorlevel 49 goto EL105DEU
goto EL105ENU
:EL105DEU
echo ERRORLEVEL=105
goto DONE
:EL105ENU
echo ERRORLEVEL=105
goto DONE

:EL104
getlang.com
if errorlevel 49 goto EL104DEU
goto EL104ENU
:EL104DEU
echo ERRORLEVEL=104
goto DONE
:EL104ENU
echo ERRORLEVEL=104
goto DONE

:EL103
getlang.com
if errorlevel 49 goto EL103DEU
goto EL103ENU
:EL103DEU
echo ERRORLEVEL=103
goto DONE
:EL103ENU
echo ERRORLEVEL=103
goto DONE

:EL102
getlang.com
if errorlevel 49 goto EL102DEU
goto EL102ENU
:EL102DEU
echo ERRORLEVEL=102
goto DONE
:EL102ENU
echo ERRORLEVEL=102
goto DONE

:EL101
getlang.com
if errorlevel 49 goto EL101DEU
goto EL101ENU
:EL101DEU
echo ERRORLEVEL=101
goto DONE
:EL101ENU
echo ERRORLEVEL=101
goto DONE

:EL100
getlang.com
if errorlevel 49 goto EL100DEU
goto EL100ENU
:EL100DEU
echo ERRORLEVEL=100
goto DONE
:EL100ENU
echo ERRORLEVEL=100
goto DONE

:EL99
getlang.com
if errorlevel 49 goto EL99DEU
goto EL99ENU
:EL99DEU
echo ERRORLEVEL=99
goto DONE
:EL99ENU
echo ERRORLEVEL=99
goto DONE

:EL98
getlang.com
if errorlevel 49 goto EL98DEU
goto EL98ENU
:EL98DEU
echo ERRORLEVEL=98
goto DONE
:EL98ENU
echo ERRORLEVEL=98
goto DONE

:EL97
getlang.com
if errorlevel 49 goto EL97DEU
goto EL97ENU
:EL97DEU
echo ERRORLEVEL=97
goto DONE
:EL97ENU
echo ERRORLEVEL=97
goto DONE

:EL96
getlang.com
if errorlevel 49 goto EL96DEU
goto EL96ENU
:EL96DEU
echo ERRORLEVEL=96
goto DONE
:EL96ENU
echo ERRORLEVEL=96
goto DONE

:EL95
getlang.com
if errorlevel 49 goto EL95DEU
goto EL95ENU
:EL95DEU
echo ERRORLEVEL=95
goto DONE
:EL95ENU
echo ERRORLEVEL=95
goto DONE

:EL94
getlang.com
if errorlevel 49 goto EL94DEU
goto EL94ENU
:EL94DEU
echo ERRORLEVEL=94
goto DONE
:EL94ENU
echo ERRORLEVEL=94
goto DONE

:EL93
getlang.com
if errorlevel 49 goto EL93DEU
goto EL93ENU
:EL93DEU
echo ERRORLEVEL=93
goto DONE
:EL93ENU
echo ERRORLEVEL=93
goto DONE

:EL92
getlang.com
if errorlevel 49 goto EL92DEU
goto EL92ENU
:EL92DEU
echo ERRORLEVEL=92
goto DONE
:EL92ENU
echo ERRORLEVEL=92
goto DONE

:EL91
getlang.com
if errorlevel 49 goto EL91DEU
goto EL91ENU
:EL91DEU
echo ERRORLEVEL=91
goto DONE
:EL91ENU
echo ERRORLEVEL=91
goto DONE

:EL90
getlang.com
if errorlevel 49 goto EL90DEU
goto EL90ENU
:EL90DEU
echo ERRORLEVEL=90
goto DONE
:EL90ENU
echo ERRORLEVEL=90
goto DONE

:EL89
getlang.com
if errorlevel 49 goto EL89DEU
goto EL89ENU
:EL89DEU
echo ERRORLEVEL=89
goto DONE
:EL89ENU
echo ERRORLEVEL=89
goto DONE

:EL88
getlang.com
if errorlevel 49 goto EL88DEU
goto EL88ENU
:EL88DEU
echo ERRORLEVEL=88
goto DONE
:EL88ENU
echo ERRORLEVEL=88
goto DONE

:EL87
getlang.com
if errorlevel 49 goto EL87DEU
goto EL87ENU
:EL87DEU
echo ERRORLEVEL=87
goto DONE
:EL87ENU
echo ERRORLEVEL=87
goto DONE

:EL86
getlang.com
if errorlevel 49 goto EL86DEU
goto EL86ENU
:EL86DEU
echo ERRORLEVEL=86
goto DONE
:EL86ENU
echo ERRORLEVEL=86
goto DONE

:EL85
getlang.com
if errorlevel 49 goto EL85DEU
goto EL85ENU
:EL85DEU
echo ERRORLEVEL=85
goto DONE
:EL85ENU
echo ERRORLEVEL=85
goto DONE

:EL84
getlang.com
if errorlevel 49 goto EL84DEU
goto EL84ENU
:EL94DEU
echo ERRORLEVEL=84
goto DONE
:EL84ENU
echo ERRORLEVEL=84
goto DONE

:EL83
getlang.com
if errorlevel 49 goto EL83DEU
goto EL83ENU
:EL83DEU
echo ERRORLEVEL=83
goto DONE
:EL83ENU
echo ERRORLEVEL=83
goto DONE

:EL82
getlang.com
if errorlevel 49 goto EL82DEU
goto EL82ENU
:EL82DEU
echo ERRORLEVEL=82
goto DONE
:EL82ENU
echo ERRORLEVEL=82
goto DONE

:EL81
getlang.com
if errorlevel 49 goto EL81DEU
goto EL81ENU
:EL81DEU
echo ERRORLEVEL=81
goto DONE
:EL81ENU
echo ERRORLEVEL=81
goto DONE

:EL80
getlang.com
if errorlevel 49 goto EL80DEU
goto EL80ENU
:EL80DEU
echo ERRORLEVEL=80
goto DONE
:EL80ENU
echo ERRORLEVEL=80
goto DONE

:EL79
getlang.com
if errorlevel 49 goto EL79DEU
goto EL79ENU
:EL79DEU
echo ERRORLEVEL=79
goto DONE
:EL79ENU
echo ERRORLEVEL=79
goto DONE

:EL78
getlang.com
if errorlevel 49 goto EL78DEU
goto EL78ENU
:EL78DEU
echo ERRORLEVEL=78
goto DONE
:EL78ENU
echo ERRORLEVEL=78
goto DONE

:EL77
getlang.com
if errorlevel 49 goto EL77DEU
goto EL77ENU
:EL77DEU
echo ERRORLEVEL=77
goto DONE
:EL77ENU
echo ERRORLEVEL=77
goto DONE

:EL76
getlang.com
if errorlevel 49 goto EL76DEU
goto EL76ENU
:EL76DEU
echo ERRORLEVEL=76
goto DONE
:EL76ENU
echo ERRORLEVEL=76
goto DONE

:EL75
getlang.com
if errorlevel 49 goto EL75DEU
goto EL75ENU
:EL75DEU
echo ERRORLEVEL=75
goto DONE
:EL75ENU
echo ERRORLEVEL=75
goto DONE

:EL74
getlang.com
if errorlevel 49 goto EL74DEU
goto EL74ENU
:EL74DEU
echo ERRORLEVEL=74
goto DONE
:EL74ENU
echo ERRORLEVEL=74
goto DONE

:EL73
getlang.com
if errorlevel 49 goto EL73DEU
goto EL73ENU
:EL73DEU
echo ERRORLEVEL=73
goto DONE
:EL255ENU
echo ERRORLEVEL=73
goto DONE

:EL72
getlang.com
if errorlevel 49 goto EL72DEU
goto EL72ENU
:EL72DEU
echo ERRORLEVEL=72
goto DONE
:EL72ENU
echo ERRORLEVEL=72
goto DONE

:EL71
getlang.com
if errorlevel 49 goto EL71DEU
goto EL71ENU
:EL71DEU
echo ERRORLEVEL=71
goto DONE
:EL71ENU
echo ERRORLEVEL=71
goto DONE

:EL70
getlang.com
if errorlevel 49 goto EL70DEU
goto EL70ENU
:EL70DEU
echo ERRORLEVEL=70
goto DONE
:EL70ENU
echo ERRORLEVEL=70
goto DONE

:EL69
getlang.com
if errorlevel 49 goto EL69DEU
goto EL69ENU
:EL69DEU
echo ERRORLEVEL=69
goto DONE
:EL69ENU
echo ERRORLEVEL=69
goto DONE

:EL68
getlang.com
if errorlevel 49 goto EL68DEU
goto EL68ENU
:EL68DEU
echo ERRORLEVEL=68
goto DONE
:EL68ENU
echo ERRORLEVEL=68
goto DONE

:EL67
getlang.com
if errorlevel 49 goto EL67DEU
goto EL67ENU
:EL1DEU
echo ERRORLEVEL=67
goto DONE
:EL67ENU
echo ERRORLEVEL=67
goto DONE

:EL66
getlang.com
if errorlevel 49 goto EL66DEU
goto EL66ENU
:EL66DEU
echo ERRORLEVEL=66
goto DONE
:EL66ENU
echo ERRORLEVEL=66
goto DONE

:EL65
getlang.com
if errorlevel 49 goto EL65DEU
goto EL65ENU
:EL65DEU
echo ERRORLEVEL=65
goto DONE
:EL65ENU
echo ERRORLEVEL=65
goto DONE

:EL64
getlang.com
if errorlevel 49 goto EL64DEU
goto EL64ENU
:EL64DEU
echo ERRORLEVEL=64
goto DONE
:EL64ENU
echo ERRORLEVEL=64
goto DONE

:EL63
getlang.com
if errorlevel 49 goto EL63DEU
goto EL63ENU
:EL63DEU
echo ERRORLEVEL=63
goto DONE
:EL63ENU
echo ERRORLEVEL=63
goto DONE

:EL62
getlang.com
if errorlevel 49 goto EL62DEU
goto EL62ENU
:EL62DEU
echo ERRORLEVEL=62
goto DONE
:EL62ENU
echo ERRORLEVEL=62
goto DONE

:EL61
getlang.com
if errorlevel 49 goto EL61DEU
goto EL61ENU
:EL61DEU
echo ERRORLEVEL=61
goto DONE
:EL61ENU
echo ERRORLEVEL=61
goto DONE

:EL60
getlang.com
if errorlevel 49 goto EL60DEU
goto EL60ENU
:EL60DEU
echo ERRORLEVEL=60
goto DONE
:EL60ENU
echo ERRORLEVEL=60
goto DONE

:EL59
getlang.com
if errorlevel 49 goto EL59DEU
goto EL59ENU
:EL59DEU
echo ERRORLEVEL=59
goto DONE
:EL59ENU
echo ERRORLEVEL=59
goto DONE

:EL58
getlang.com
if errorlevel 49 goto EL58DEU
goto EL58ENU
:EL58DEU
echo ERRORLEVEL=58
goto DONE
:EL58ENU
echo ERRORLEVEL=58
goto DONE

:EL57
getlang.com
if errorlevel 49 goto EL57DEU
goto EL57ENU
:EL57DEU
echo ERRORLEVEL=57
goto DONE
:EL57ENU
echo ERRORLEVEL=57
goto DONE

:EL56
getlang.com
if errorlevel 49 goto EL56DEU
goto EL56ENU
:EL56DEU
echo ERRORLEVEL=56
goto DONE
:EL56ENU
echo ERRORLEVEL=56
goto DONE

:EL55
getlang.com
if errorlevel 49 goto EL55DEU
goto EL55ENU
:EL55DEU
echo ERRORLEVEL=55
goto DONE
:EL55ENU
echo ERRORLEVEL=55
goto DONE

:EL54
getlang.com
if errorlevel 49 goto EL54DEU
goto EL54ENU
:EL54DEU
echo ERRORLEVEL=54
goto DONE
:EL54ENU
echo ERRORLEVEL=54
goto DONE

:EL53
getlang.com
if errorlevel 49 goto EL53DEU
goto EL53ENU
:EL53DEU
echo ERRORLEVEL=53
goto DONE
:EL53ENU
echo ERRORLEVEL=53
goto DONE

:EL52
getlang.com
if errorlevel 49 goto EL52DEU
goto EL52ENU
:EL52DEU
echo ERRORLEVEL=52
goto DONE
:EL52ENU
echo ERRORLEVEL=52
goto DONE

:EL51
getlang.com
if errorlevel 49 goto EL51DEU
goto EL51ENU
:EL51DEU
echo ERRORLEVEL=51 Druckerfehler
goto DONE
:EL51ENU
echo ERRORLEVEL=51 printer error
goto DONE

:EL50
getlang.com
if errorlevel 49 goto EL50DEU
goto EL50ENU
:EL50DEU
echo ERRORLEVEL=50 Netzwerkressource nicht verfügbar
goto DONE
:EL50ENU
echo ERRORLEVEL=50 network resource not available
goto DONE

:EL49
getlang.com
if errorlevel 49 goto EL49DEU
goto EL49ENU
:EL49DEU
echo ERRORLEVEL=49 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL49ENU
echo ERRORLEVEL=49 device / driver / system error (dynamic)
goto DONE

:EL48
getlang.com
if errorlevel 49 goto EL48DEU
goto EL48ENU
:EL48DEU
echo ERRORLEVEL=48 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL48ENU
echo ERRORLEVEL=48 device / driver / system error (dynamic)
goto DONE

:EL47
getlang.com
if errorlevel 49 goto EL47DEU
goto EL47ENU
:EL47DEU
echo ERRORLEVEL=47 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL47ENU
echo ERRORLEVEL=47 device / driver / system error (dynamic)
goto DONE

:EL46
getlang.com
if errorlevel 49 goto EL46DEU
goto EL46ENU
:EL46DEU
echo ERRORLEVEL=46 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL46ENU
echo ERRORLEVEL=46 device / driver / system error (dynamic)
goto DONE

:EL45
getlang.com
if errorlevel 49 goto EL45DEU
goto EL45ENU
:EL45DEU
echo ERRORLEVEL=45 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL45ENU
echo ERRORLEVEL=45 device / driver / system error (dynamic)
goto DONE

:EL44
getlang.com
if errorlevel 49 goto EL44DEU
goto EL44ENU
:EL44DEU
echo ERRORLEVEL=44 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL44ENU
echo ERRORLEVEL=44 device / driver / system error (dynamic)
goto DONE

:EL43
getlang.com
if errorlevel 49 goto EL43DEU
goto EL43ENU
:EL43DEU
echo ERRORLEVEL=43 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL43ENU
echo ERRORLEVEL=43 device / driver / system error (dynamic)
goto DONE

:EL42
getlang.com
if errorlevel 49 goto EL42DEU
goto EL42ENU
:EL42DEU
echo ERRORLEVEL=42 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL42ENU
echo ERRORLEVEL=42 device / driver / system error (dynamic)
goto DONE

:EL41
getlang.com
if errorlevel 49 goto EL41DEU
goto EL41ENU
:EL41DEU
echo ERRORLEVEL=41 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL41ENU
echo ERRORLEVEL=41 device / driver / system error (dynamic)
goto DONE

:EL40
getlang.com
if errorlevel 49 goto EL40DEU
goto EL49ENU
:EL40DEU
echo ERRORLEVEL=40 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL40ENU
echo ERRORLEVEL=40 device / driver / system error (dynamic)
goto DONE

:EL39
getlang.com
if errorlevel 49 goto EL39DEU
goto EL39ENU
:EL39DEU
echo ERRORLEVEL=39 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL39ENU
echo ERRORLEVEL=39 device / driver / system error (dynamic)
goto DONE

:EL38
getlang.com
if errorlevel 49 goto EL38DEU
goto EL38ENU
:EL38DEU
echo ERRORLEVEL=38 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL38ENU
echo ERRORLEVEL=38 device / driver / system error (dynamic)
goto DONE

:EL37
getlang.com
if errorlevel 49 goto EL37DEU
goto EL37ENU
:EL37DEU
echo ERRORLEVEL=37 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL37ENU
echo ERRORLEVEL=37 device / driver / system error (dynamic)
goto DONE

:EL36
getlang.com
if errorlevel 49 goto EL36DEU
goto EL36ENU
:EL36DEU
echo ERRORLEVEL=36 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL36ENU
echo ERRORLEVEL=36 device / driver / system error (dynamic)
goto DONE

:EL35
getlang.com
if errorlevel 49 goto EL35DEU
goto EL35ENU
:EL35DEU
echo ERRORLEVEL=35 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL35ENU
echo ERRORLEVEL=35 device / driver / system error (dynamic)
goto DONE

:EL34
getlang.com
if errorlevel 49 goto EL34DEU
goto EL34ENU
:EL34DEU
echo ERRORLEVEL=34 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL34ENU
echo ERRORLEVEL=34 device / driver / system error (dynamic)
goto DONE

:EL33
getlang.com
if errorlevel 49 goto EL33DEU
goto EL33ENU
:EL33DEU
echo ERRORLEVEL=33 Geräte-/Treiber-/Systemfehler (variabel)
goto DONE
:EL33ENU
echo ERRORLEVEL=33 device / driver / system error (dynamic)
goto DONE

:EL32
getlang.com
if errorlevel 49 goto EL32DEU
goto EL32ENU
:EL32DEU
echo ERRORLEVEL=32 Dateisystemfehler / falsche DOS-Version
goto DONE
:EL32ENU
echo ERRORLEVEL=32 file system error / wrong DOS-Version
goto DONE

:EL31
getlang.com
if errorlevel 49 goto EL31DEU
goto EL31ENU
:EL31DEU
echo ERRORLEVEL=31 Ungültige Länge
goto DONE
:EL31ENU
echo ERRORLEVEL=31 length invalid
goto DONE

:EL30
getlang.com
if errorlevel 49 goto EL30DEU
goto EL30ENU
:EL30DEU
echo ERRORLEVEL=30 Formatfehler
goto DONE
:EL30ENU
echo ERRORLEVEL=30 format error
goto DONE

:EL29
getlang.com
if errorlevel 49 goto EL29DEU
goto EL29ENU
:EL29DEU
echo ERRORLEVEL=29 Funktion nicht unterstützt
goto DONE
:EL29ENU
echo ERRORLEVEL=29 feature not supported
goto DONE

:EL28
getlang.com
if errorlevel 49 goto EL28DEU
goto EL28ENU
:EL28DEU
echo ERRORLEVEL=28 Seek-Fehler
goto DONE
:EL28ENU
echo ERRORLEVEL=28 seek error
goto DONE

:EL27
getlang.com
if errorlevel 49 goto EL27DEU
goto EL27ENU
:EL27DEU
echo ERRORLEVEL=27 CRC-Fehler
goto DONE
:EL27ENU
echo ERRORLEVEL=27 crc error
goto DONE

:EL26
getlang.com
if errorlevel 49 goto EL26DEU
goto EL26ENU
:EL26DEU
echo ERRORLEVEL=26 Ungültiges Medium
goto DONE
:EL26ENU
echo ERRORLEVEL=26 unknow media
goto DONE

:EL25
getlang.com
if errorlevel 49 goto EL25DEU
goto EL25ENU
:EL25DEU
echo ERRORLEVEL=25 Medium nicht bereit / Laufwerk nicht bereit
goto DONE
:EL25ENU
echo ERRORLEVEL=25 drive is not ready
goto DONE

:EL24
getlang.com
if errorlevel 49 goto EL24DEU
goto EL24ENU
:EL24DEU
echo ERRORLEVEL=24 Lock-Verletzung
goto DONE
:EL24NU
echo ERRORLEVEL=24 lock violation
goto DONE

:EL23
getlang.com
if errorlevel 49 goto EL23DEU
goto EL1ENU
:EL23DEU
echo ERRORLEVEL=23 Sharing-Verletzung
goto DONE
:EL23ENU
echo ERRORLEVEL=23 share violation
goto DONE

:EL22
getlang.com
if errorlevel 49 goto EL22DEU
goto EL22ENU
:EL22DEU
echo ERRORLEVEL=22 Allgemeiner Gerätefehler
goto DONE
:EL22ENU
echo ERRORLEVEL=22 common drive error
goto DONE

:EL21
getlang.com
if errorlevel 49 goto EL21DEU
goto EL21ENU
:EL21DEU
echo ERRORLEVEL=21 Schreibfehler
goto DONE
:EL21ENU
echo ERRORLEVEL=21 write error
goto DONE

:EL20
getlang.com
if errorlevel 49 goto EL20DEU
goto EL1ENU
:EL20DEU
echo ERRORLEVEL=20 Lesefehler
goto DONE
:EL20ENU
echo ERRORLEVEL=20 read error
goto DONE

:EL19
getlang.com
if errorlevel 49 goto EL19DEU
goto EL19ENU
:EL19DEU
echo ERRORLEVEL=19 Datenträger schreibgeschützt
goto DONE
:EL19ENU
echo ERRORLEVEL=19 drive is read-only
goto DONE

:EL18
getlang.com
if errorlevel 49 goto EL18DEU
goto EL18ENU
:EL18DEU
echo ERRORLEVEL=18 Keine weiteren Dateien
goto DONE
:EL18ENU
echo ERRORLEVEL=18 no more files
goto DONE

:EL17
getlang.com
if errorlevel 49 goto EL17DEU
goto EL17ENU
:EL17DEU
echo ERRORLEVEL=17 Nicht derselbe Laufwerkstyp
goto DONE
:EL17ENU
echo ERRORLEVEL=17 wrong drive type
goto DONE

:EL16
getlang.com
if errorlevel 49 goto EL16DEU
goto EL16ENU
:EL16DEU
echo ERRORLEVEL=16 Aktuelles Verzeichnis kann nicht gelöscht werden
goto DONE
:EL16ENU
echo ERRORLEVEL=16 current directory can not delete
goto DONE

:EL15
getlang.com
if errorlevel 49 goto EL15DEU
goto EL15ENU
:EL15DEU
echo ERRORLEVEL=15 Laufwerk nicht vorhanden/ungültig
goto DONE
:EL15ENU
echo ERRORLEVEL=15 drive invalid
goto DONE

:EL14
getlang.com
if errorlevel 49 goto EL14DEU
goto EL14ENU
:EL14DEU
echo ERRORLEVEL=14 Datei existiert bereits
goto DONE
:EL14ENU
echo ERRORLEVEL=14 file already exists
goto DONE

:EL13
getlang.com
if errorlevel 49 goto EL13DEU
goto EL13ENU
:EL13DEU
echo ERRORLEVEL=13 Ungültiges Laufwerk
goto DONE
:EL13ENU
echo ERRORLEVEL=13 drive invalid
goto DONE

:EL12
getlang.com
if errorlevel 49 goto EL12DEU
goto EL12ENU
:EL12DEU
echo ERRORLEVEL=12 Ungültige Zugriffskennung
goto DONE
:EL12ENU
echo ERRORLEVEL=12 access token invalid
goto DONE

:EL11
getlang.com
if errorlevel 49 goto EL11DEU
goto EL11ENU
:EL11DEU
echo ERRORLEVEL=11 Falsches Format / ungültige EXE
goto DONE
:EL11ENU
echo ERRORLEVEL=11 invalid file format
goto DONE

:EL10
getlang.com
if errorlevel 49 goto EL10DEU
goto EL10ENU
:EL10DEU
echo ERRORLEVEL=10 Falsche Umgebung
goto DONE
:EL10ENU
echo ERRORLEVEL=10 environment invalid
goto DONE

:EL9
getlang.com
if errorlevel 49 goto EL9DEU
goto EL9ENU
:EL9DEU
echo ERRORLEVEL=9 Ungültiger Speicherblock
goto DONE
:EL9ENU
echo ERRORLEVEL=9 memory block invalid
goto DONE

:EL8
getlang.com
if errorlevel 49 goto EL8DEU
goto EL8ENU
:EL8DEU
echo ERRORLEVEL=8 Zu wenig Speicher
goto DONE
:EL8ENU
echo ERRORLEVEL=8 insufficient memory
goto DONE

:EL7
getlang.com
if errorlevel 49 goto EL7DEU
goto EL7ENU
:EL7DEU
echo ERRORLEVEL=7 Speicherverwaltungsblöcke beschädigt
goto DONE
:EL7ENU
echo ERRORLEVEL=7 memory blocks damages
goto DONE

:EL6
getlang.com
if errorlevel 49 goto EL6DEU
goto EL6ENU
:EL6DEU
echo ERRORLEVEL=6 Ungültiger Handle
goto DONE
:EL6ENU
echo ERRORLEVEL=6 invalid handle
goto DONE

:EL5
getlang.com
if errorlevel 49 goto EL5DEU
goto EL1ENU
:EL5DEU
echo ERRORLEVEL=5 Zugriff verweigert (Access denied)
goto DONE
:EL5ENU
echo ERRORLEVEL=5 access denied
goto DONE

:EL4
getlang.com
if errorlevel 49 goto EL4DEU
goto EL4ENU
:EL4DEU
echo ERRORLEVEL=4 Zu viele offene Dateien
goto DONE
:EL4ENU
echo ERRORLEVEL=4 too many open files
goto DONE

:EL3
getlang.com
if errorlevel 49 goto EL3DEU
goto EL3ENU
:EL3DEU
echo ERRORLEVEL=3 Pfad nicht gefunden
goto DONE
:EL3ENU
echo ERRORLEVEL=250 path not found
goto DONE

:EL2
getlang.com
if errorlevel 49 goto EL2DEU
goto EL2ENU
:EL2DEU
echo ERRORLEVEL=2 Datei nicht gefunden
goto DONE
:EL2ENU
echo ERRORLEVEL=2 file not found
goto DONE

:EL1
getlang.com
if errorlevel 49 goto EL1DEU
goto EL1ENU
:EL1DEU
echo ERRORLEVEL=1 Allgemeiner Fehler
goto DONE
:EL1ENU
echo ERRORLEVEL=1 Common Error
goto DONE

:EL0
getlang.com
if errorlevel 49 goto EL0DEU
goto EL0ENU
:EL0DEU
echo ERRORLEVEL=0 Erfolg
goto DONE
:EL0ENU
echo ERRORLEVEL=0 Success
goto DONE

:done
