# ----------------------------------------------------------------------
# ATTENTION:
# automated generated - any change on this file will be lost
# (c) 2024 by paule32 - Jens Kallup <pule32.jk@gmail.com>
# ----------------------------------------------------------------------
def load_flags:
    cdn_host = genv.__app__cdn_host + "/observer/img/flags/"
    cdn_suff = ".gif"
    genv.v__app__cdn_flags = [
        [ "AFG", cdn_host + "AFG" + cdn_suff, "Afghanistan" ],
        [ "ALB", cdn_host + "ALB" + cdn_suff, "Albania" ],
        [ "DZA", cdn_host + "DZA" + cdn_suff, "Algeria" ],
        [ "AND", cdn_host + "AND" + cdn_suff, "Andorra" ],
        [ "AGO", cdn_host + "AGO" + cdn_suff, "Angola" ],
        [ "ATG", cdn_host + "ATG" + cdn_suff, "Antigua and Barbuda" ],
        [ "ARG", cdn_host + "ARG" + cdn_suff, "Argentina" ],
        [ "ARM", cdn_host + "ARM" + cdn_suff, "Armenia" ],
        [ "AUS", cdn_host + "AUS" + cdn_suff, "Australia" ],
        [ "AUT", cdn_host + "AUT" + cdn_suff, "Austria" ],
        [ "AZE", cdn_host + "AZE" + cdn_suff, "Azerbaijan" ],
        [ "BHS", cdn_host + "BHS" + cdn_suff, "Bahamas (the)" ],
        [ "BHR", cdn_host + "BHR" + cdn_suff, "Bahrain" ],
        [ "BGD", cdn_host + "BGD" + cdn_suff, "Bangladesh" ],
        [ "BRB", cdn_host + "BRB" + cdn_suff, "Barbados" ],
        [ "BLR", cdn_host + "BLR" + cdn_suff, "Belarus" ],
        [ "BEL", cdn_host + "BEL" + cdn_suff, "Belgium" ],
        [ "BLZ", cdn_host + "BLZ" + cdn_suff, "Belize" ],
        [ "BEN", cdn_host + "BEN" + cdn_suff, "Benin" ],
        [ "BTN", cdn_host + "BTN" + cdn_suff, "Bhutan" ],
        [ "BOL", cdn_host + "BOL" + cdn_suff, "Bolivia (Plurinational State of)" ],
        [ "BIH", cdn_host + "BIH" + cdn_suff, "Bosnia and Herzegovina" ],
        [ "BWA", cdn_host + "BWA" + cdn_suff, "Botswana" ],
        [ "BRA", cdn_host + "BRA" + cdn_suff, "Brazil" ],
        [ "BRN", cdn_host + "BRN" + cdn_suff, "Brunei Darussalam" ],
        [ "BGR", cdn_host + "BGR" + cdn_suff, "Bulgaria" ],
        [ "BFA", cdn_host + "BFA" + cdn_suff, "Burkina Faso" ],
        [ "BDI", cdn_host + "BDI" + cdn_suff, "Burundi" ],
        [ "CPV", cdn_host + "CPV" + cdn_suff, "Cabo Verde" ],
        [ "KHM", cdn_host + "KHM" + cdn_suff, "Cambodia" ],
        [ "CMR", cdn_host + "CMR" + cdn_suff, "Cameroon" ],
        [ "CAN", cdn_host + "CAN" + cdn_suff, "Canada" ],
        [ "CAF", cdn_host + "CAF" + cdn_suff, "Central African Republic (the)" ],
        [ "TCD", cdn_host + "TCD" + cdn_suff, "Chad" ],
        [ "CHL", cdn_host + "CHL" + cdn_suff, "Chile" ],
        [ "CHN", cdn_host + "CHN" + cdn_suff, "China" ],
        [ "COL", cdn_host + "COL" + cdn_suff, "Colombia" ],
        [ "COM", cdn_host + "COM" + cdn_suff, "Comoros (the)" ],
        [ "COD", cdn_host + "COD" + cdn_suff, "Congo (the Democratic Republic of the)" ],
        [ "COG", cdn_host + "COG" + cdn_suff, "Congo (the)" ],
        [ "CRI", cdn_host + "CRI" + cdn_suff, "Costa Rica" ],
        [ "CIV", cdn_host + "CIV" + cdn_suff, "Côte d'Ivoire" ],
        [ "HRV", cdn_host + "HRV" + cdn_suff, "Croatia" ],
        [ "CUB", cdn_host + "CUB" + cdn_suff, "Cuba" ],
        [ "CYP", cdn_host + "CYP" + cdn_suff, "Cyprus" ],
        [ "CZE", cdn_host + "CZE" + cdn_suff, "Czechia" ],
        [ "DNK", cdn_host + "DNK" + cdn_suff, "Denmark" ],
        [ "DJI", cdn_host + "DJI" + cdn_suff, "Djibouti" ],
        [ "DMA", cdn_host + "DMA" + cdn_suff, "Dominica" ],
        [ "DOM", cdn_host + "DOM" + cdn_suff, "Dominican Republic (the)" ],
        [ "ECU", cdn_host + "ECU" + cdn_suff, "Ecuador" ],
        [ "EGY", cdn_host + "EGY" + cdn_suff, "Egypt" ],
        [ "SLV", cdn_host + "SLV" + cdn_suff, "El Salvador" ],
        [ "GNQ", cdn_host + "GNQ" + cdn_suff, "Equatorial Guinea" ],
        [ "ERI", cdn_host + "ERI" + cdn_suff, "Eritrea" ],
        [ "EST", cdn_host + "EST" + cdn_suff, "Estonia" ],
        [ "SWZ", cdn_host + "SWZ" + cdn_suff, "Eswatini" ],
        [ "ETH", cdn_host + "ETH" + cdn_suff, "Ethiopia" ],
        [ "FJI", cdn_host + "FJI" + cdn_suff, "Fiji" ],
        [ "FIN", cdn_host + "FIN" + cdn_suff, "Finland" ],
        [ "FRA", cdn_host + "FRA" + cdn_suff, "France" ],
        [ "GAB", cdn_host + "GAB" + cdn_suff, "Gabon" ],
        [ "GMB", cdn_host + "GMB" + cdn_suff, "Gambia (the)" ],
        [ "GEO", cdn_host + "GEO" + cdn_suff, "Georgia" ],
        [ "DEU", cdn_host + "DEU" + cdn_suff, "Germany" ],
        [ "GHA", cdn_host + "GHA" + cdn_suff, "Ghana" ],
        [ "GRC", cdn_host + "GRC" + cdn_suff, "Greece" ],
        [ "GRD", cdn_host + "GRD" + cdn_suff, "Grenada" ],
        [ "GTM", cdn_host + "GTM" + cdn_suff, "Guatemala" ],
        [ "GIN", cdn_host + "GIN" + cdn_suff, "Guinea" ],
        [ "GNB", cdn_host + "GNB" + cdn_suff, "Guinea-Bissau" ],
        [ "GUY", cdn_host + "GUY" + cdn_suff, "Guyana" ],
        [ "HTI", cdn_host + "HTI" + cdn_suff, "Haiti" ],
        [ "VAT", cdn_host + "VAT" + cdn_suff, "Holy See (the)" ],
        [ "HND", cdn_host + "HND" + cdn_suff, "Honduras" ],
        [ "HUN", cdn_host + "HUN" + cdn_suff, "Hungary" ],
        [ "ISL", cdn_host + "ISL" + cdn_suff, "Iceland" ],
        [ "IND", cdn_host + "IND" + cdn_suff, "India" ],
        [ "IDN", cdn_host + "IDN" + cdn_suff, "Indonesia" ],
        [ "IRN", cdn_host + "IRN" + cdn_suff, "Iran (Islamic Republic of)" ],
        [ "IRQ", cdn_host + "IRQ" + cdn_suff, "Iraq" ],
        [ "IRL", cdn_host + "IRL" + cdn_suff, "Ireland" ],
        [ "ISR", cdn_host + "ISR" + cdn_suff, "Israel" ],
        [ "ITA", cdn_host + "ITA" + cdn_suff, "Italy" ],
        [ "JAM", cdn_host + "JAM" + cdn_suff, "Jamaica" ],
        [ "JPN", cdn_host + "JPN" + cdn_suff, "Japan" ],
        [ "JOR", cdn_host + "JOR" + cdn_suff, "Jordan" ],
        [ "KAZ", cdn_host + "KAZ" + cdn_suff, "Kazakhstan" ],
        [ "KEN", cdn_host + "KEN" + cdn_suff, "Kenya" ],
        [ "KIR", cdn_host + "KIR" + cdn_suff, "Kiribati" ],
        [ "PRK", cdn_host + "PRK" + cdn_suff, "Korea (the Democratic People's Republic of)" ],
        [ "KOR", cdn_host + "KOR" + cdn_suff, "Korea (the Republic of)" ],
        [ "KWT", cdn_host + "KWT" + cdn_suff, "Kuwait" ],
        [ "KGZ", cdn_host + "KGZ" + cdn_suff, "Kyrgyzstan" ],
        [ "LAO", cdn_host + "LAO" + cdn_suff, "Lao People's Democratic Republic (the)" ],
        [ "LVA", cdn_host + "LVA" + cdn_suff, "Latvia" ],
        [ "LBN", cdn_host + "LBN" + cdn_suff, "Lebanon" ],
        [ "LSO", cdn_host + "LSO" + cdn_suff, "Lesotho" ],
        [ "LBR", cdn_host + "LBR" + cdn_suff, "Liberia" ],
        [ "LBY", cdn_host + "LBY" + cdn_suff, "Libya" ],
        [ "LIE", cdn_host + "LIE" + cdn_suff, "Liechtenstein" ],
        [ "LTU", cdn_host + "LTU" + cdn_suff, "Lithuania" ],
        [ "LUX", cdn_host + "LUX" + cdn_suff, "Luxembourg" ],
        [ "MDG", cdn_host + "MDG" + cdn_suff, "Madagascar" ],
        [ "MWI", cdn_host + "MWI" + cdn_suff, "Malawi" ],
        [ "MYS", cdn_host + "MYS" + cdn_suff, "Malaysia" ],
        [ "MDV", cdn_host + "MDV" + cdn_suff, "Maldives" ],
        [ "MLI", cdn_host + "MLI" + cdn_suff, "Mali" ],
        [ "MLT", cdn_host + "MLT" + cdn_suff, "Malta" ],
        [ "MHL", cdn_host + "MHL" + cdn_suff, "Marshall Islands (the)" ],
        [ "MRT", cdn_host + "MRT" + cdn_suff, "Mauritania" ],
        [ "MUS", cdn_host + "MUS" + cdn_suff, "Mauritius" ],
        [ "MEX", cdn_host + "MEX" + cdn_suff, "Mexico" ],
        [ "FSM", cdn_host + "FSM" + cdn_suff, "Micronesia (Federated States of)" ],
        [ "MDA", cdn_host + "MDA" + cdn_suff, "Moldova (the Republic of)" ],
        [ "MCO", cdn_host + "MCO" + cdn_suff, "Monaco" ],
        [ "MNG", cdn_host + "MNG" + cdn_suff, "Mongolia" ],
        [ "MNE", cdn_host + "MNE" + cdn_suff, "Montenegro" ],
        [ "MAR", cdn_host + "MAR" + cdn_suff, "Morocco" ],
        [ "MOZ", cdn_host + "MOZ" + cdn_suff, "Mozambique" ],
        [ "MMR", cdn_host + "MMR" + cdn_suff, "Myanmar" ],
        [ "NAM", cdn_host + "NAM" + cdn_suff, "Namibia" ],
        [ "NRU", cdn_host + "NRU" + cdn_suff, "Nauru" ],
        [ "NPL", cdn_host + "NPL" + cdn_suff, "Nepal" ],
        [ "NLD", cdn_host + "NLD" + cdn_suff, "Netherlands (the)" ],
        [ "NZL", cdn_host + "NZL" + cdn_suff, "New Zealand" ],
        [ "NIC", cdn_host + "NIC" + cdn_suff, "Nicaragua" ],
        [ "NER", cdn_host + "NER" + cdn_suff, "Niger (the)" ],
        [ "NGA", cdn_host + "NGA" + cdn_suff, "Nigeria" ],
        [ "NOR", cdn_host + "NOR" + cdn_suff, "Norway" ],
        [ "OMN", cdn_host + "OMN" + cdn_suff, "Oman" ],
        [ "PAK", cdn_host + "PAK" + cdn_suff, "Pakistan" ],
        [ "PLW", cdn_host + "PLW" + cdn_suff, "Palau" ],
        [ "PSE", cdn_host + "PSE" + cdn_suff, "Palestine, State of" ],
        [ "PAN", cdn_host + "PAN" + cdn_suff, "Panama" ],
        [ "PNG", cdn_host + "PNG" + cdn_suff, "Papua New Guinea" ],
        [ "PRY", cdn_host + "PRY" + cdn_suff, "Paraguay" ],
        [ "PER", cdn_host + "PER" + cdn_suff, "Peru" ],
        [ "PHL", cdn_host + "PHL" + cdn_suff, "Philippines (the)" ],
        [ "POL", cdn_host + "POL" + cdn_suff, "Poland" ],
        [ "PRT", cdn_host + "PRT" + cdn_suff, "Portugal" ],
        [ "QAT", cdn_host + "QAT" + cdn_suff, "Qatar" ],
        [ "MKD", cdn_host + "MKD" + cdn_suff, "Republic of North Macedonia" ],
        [ "ROU", cdn_host + "ROU" + cdn_suff, "Romania" ],
        [ "RUS", cdn_host + "RUS" + cdn_suff, "Russian Federation (the)" ],
        [ "RWA", cdn_host + "RWA" + cdn_suff, "Rwanda" ],
        [ "KNA", cdn_host + "KNA" + cdn_suff, "Saint Kitts and Nevis" ],
        [ "LCA", cdn_host + "LCA" + cdn_suff, "Saint Lucia" ],
        [ "VCT", cdn_host + "VCT" + cdn_suff, "Saint Vincent and the Grenadines" ],
        [ "WSM", cdn_host + "WSM" + cdn_suff, "Samoa" ],
        [ "SMR", cdn_host + "SMR" + cdn_suff, "San Marino" ],
        [ "STP", cdn_host + "STP" + cdn_suff, "Sao Tome and Principe" ],
        [ "SAU", cdn_host + "SAU" + cdn_suff, "Saudi Arabia" ],
        [ "SEN", cdn_host + "SEN" + cdn_suff, "Senegal" ],
        [ "SRB", cdn_host + "SRB" + cdn_suff, "Serbia" ],
        [ "SYC", cdn_host + "SYC" + cdn_suff, "Seychelles" ],
        [ "SLE", cdn_host + "SLE" + cdn_suff, "Sierra Leone" ],
        [ "SGP", cdn_host + "SGP" + cdn_suff, "Singapore" ],
        [ "SVK", cdn_host + "SVK" + cdn_suff, "Slovakia" ],
        [ "SVN", cdn_host + "SVN" + cdn_suff, "Slovenia" ],
        [ "SLB", cdn_host + "SLB" + cdn_suff, "Solomon Islands" ],
        [ "SOM", cdn_host + "SOM" + cdn_suff, "Somalia" ],
        [ "ZAF", cdn_host + "ZAF" + cdn_suff, "South Africa" ],
        [ "SSD", cdn_host + "SSD" + cdn_suff, "South Sudan" ],
        [ "ESP", cdn_host + "ESP" + cdn_suff, "Spain" ],
        [ "LKA", cdn_host + "LKA" + cdn_suff, "Sri Lanka" ],
        [ "SDN", cdn_host + "SDN" + cdn_suff, "Sudan (the)" ],
        [ "SUR", cdn_host + "SUR" + cdn_suff, "Suriname" ],
        [ "SWE", cdn_host + "SWE" + cdn_suff, "Sweden" ],
        [ "CHE", cdn_host + "CHE" + cdn_suff, "Switzerland" ],
        [ "SYR", cdn_host + "SYR" + cdn_suff, "Syrian Arab Republic" ],
        [ "TJK", cdn_host + "TJK" + cdn_suff, "Tajikistan" ],
        [ "TZA", cdn_host + "TZA" + cdn_suff, "Tanzania, United Republic of" ],
        [ "THA", cdn_host + "THA" + cdn_suff, "Thailand" ],
        [ "TLS", cdn_host + "TLS" + cdn_suff, "Timor-Leste" ],
        [ "TGO", cdn_host + "TGO" + cdn_suff, "Togo" ],
        [ "TON", cdn_host + "TON" + cdn_suff, "Tonga" ],
        [ "TTO", cdn_host + "TTO" + cdn_suff, "Trinidad and Tobago" ],
        [ "TUN", cdn_host + "TUN" + cdn_suff, "Tunisia" ],
        [ "TUR", cdn_host + "TUR" + cdn_suff, "Turkey" ],
        [ "TKM", cdn_host + "TKM" + cdn_suff, "Turkmenistan" ],
        [ "TUV", cdn_host + "TUV" + cdn_suff, "Tuvalu" ],
        [ "UGA", cdn_host + "UGA" + cdn_suff, "Uganda" ],
        [ "UKR", cdn_host + "UKR" + cdn_suff, "Ukraine" ],
        [ "ARE", cdn_host + "ARE" + cdn_suff, "United Arab Emirates (the)" ],
        [ "GBR", cdn_host + "GBR" + cdn_suff, "United Kingdom of Great Britain and Northern Ireland (the)" ],
        [ "USA", cdn_host + "USA" + cdn_suff, "United States of America (the)" ],
        [ "URY", cdn_host + "URY" + cdn_suff, "Uruguay" ],
        [ "UZB", cdn_host + "UZB" + cdn_suff, "Uzbekistan" ],
        [ "VUT", cdn_host + "VUT" + cdn_suff, "Vanuatu" ],
        [ "VEN", cdn_host + "VEN" + cdn_suff, "Venezuela (Bolivarian Republic of)" ],
        [ "VNM", cdn_host + "VNM" + cdn_suff, "Viet Nam" ],
        [ "YEM", cdn_host + "YEM" + cdn_suff, "Yemen" ],
        [ "ZMB", cdn_host + "ZMB" + cdn_suff, "Zambia" ],
        [ "ZWE", cdn_host + "ZWE" + cdn_suff, "Zimbabwe" ],
    ]
