# generated by dBaseToPython (runtime-backed)
from dBaseRuntime import RT, EntryPoint

rt = RT()

def main():
    rt.SET_NAME('Y', 12)
    rt.SET_NAME('X', 23)
    
    rt.WRITE("XXX", 12, [ 'ddd', 444])
    rt.WRITE(rt.GET('X', []))
    rt.WRITE(rt.GET('Y', []))

"""
    rt.WRITE(rt.BINOP("Hello", '+', "World"))
    rt.SET_NAME('X', 23)
    rt.SET_NAME('X', rt.BINOP(rt.PRIMARY('X'), '+', 1))
    if rt.TRUE(rt.BINOP(rt.PRIMARY('X'), '==', 22)):
        rt.WRITE(rt.BINOP("X := ", '+', rt.GET(x, [])))
    if rt.TRUE(rt.BINOP(2, '==', rt.BINOP(rt.PRIMARY('x'), '+', 1))):
        rt.WRITE("falsch")
    else:
        if rt.TRUE(rt.BINOP(3, '<', 3)):
            rt.WRITE(rt.BINOP(rt.BINOP("huch", '+', " hach"), '+', 'xxxx'))
        else:
            rt.WRITE("sonst")
        rt.WRITE("naja")
        if rt.TRUE(rt.BINOP(rt.PRIMARY('x'), '==', 23)):
            rt.WRITE("2222")
        rt.SET_NAME('X', rt.BINOP(rt.PRIMARY('X'), '+', 1))
        if rt.TRUE(rt.BINOP(rt.PRIMARY('X'), '==', 24)):
            rt.WRITE("OKAY")
    rt.PARAMETER(['bmodal'])
    rt.SET_NAME('B', None)
    rt.SET_NAME('B', rt.NEW('ParentForm', 51, 4))
    rt.CALL_ANY(rt.PRIMARY('B.Init'), [121, 2])
    rt.CALL_ANY(rt.PRIMARY('B.Open'), [])
    class ParentForm(FORM):
        def __init__(self, *args):
            super().__init__()
            self._instance = rt.MAKE_INSTANCE(self, args)
        
        def init(self, a, c):
            this = self
            rt.WRITE("ParentForm.Init()")
            rt.WRITE(rt.BINOP(rt.PRIMARY('a'), '+', 10))
            rt.WRITE(rt.BINOP(rt.PRIMARY('a'), '+', 2))
            rt.WRITE(rt.GET(pushbutton1, []))
            rt.SET_NAME('I', 1)
            rt.SET_NAME('E', 42)
            for i in rt.RANGE_INCL(1, 3, 1):
                rt.WRITE(rt.BINOP("I = ", '+', rt.GET(i, [])))
                rt.SET_NAME('E', rt.BINOP(rt.PRIMARY('E'), '+', 1))
                rt.WRITE(rt.GET(e, []))
                rt.WRITE(rt.BINOP("x= ", '+', rt.CALL_ANY(rt.PRIMARY('THIS.TestProc'), [rt.PRIMARY('THIS'), "text 1"])))
                rt.WRITE(rt.BINOP(rt.BINOP("--> ", '+', rt.GET(width, [])), '+', " okay."))
                if rt.TRUE(rt.BINOP(rt.PRIMARY('I'), '==', 3)):
                    return
                break
            rt.WRITE("go along")
        
        def testproc(self, sender):
            this = self
            rt.WRITE(rt.GET(sender, []))
            return 324
        
        def parentform_onclick(self, sender):
            this = self
            rt.WRITE("on form clicked")
            rt.SET_NAME('x', 5)
            rt.WRITE(rt.GET(x, []))
            while rt.TRUE(rt.BINOP(rt.PRIMARY('x'), '>=', 2)):
                rt.WRITE(rt.GET(x, []))
                rt.SET_NAME('x', rt.BINOP(rt.PRIMARY('x'), '-', 1))
                if rt.TRUE(rt.BINOP(rt.PRIMARY('x'), '==', 3)):
                    break
            rt.WRITE("----->")
            rt.CREATE_FILE("33.txt")
        
        def pushbutton1_onclick_1(self, sender):
            this = self
            rt.WRITE("clicked button A: handler 1")
            rt.WRITE(rt.GET(sender, ['Text']))
            _t1 = rt.GET(sender, [])
            rt.PUSH_WITH(_t1)
            rt.WRITE(rt.GET(text, []))
            _t2 = rt.GET(font, [])
            rt.PUSH_WITH(_t2)
            rt.WITH_SET(['bold'], True)
            rt.WITH_SET(['size'], 14)
            rt.POP_WITH()
            rt.POP_WITH()
            if rt.TRUE(rt.BINOP(rt.PRIMARY('THIS.PushButton1.Text'), '==', "Click Me")):
                rt.SET_NAME('THIS.PushButton2.Text', "Click Me")
                rt.WRITE("okk")
                _t3 = rt.GET(sender, [])
                rt.PUSH_WITH(_t3)
                rt.WITH_SET(['Text'], "Click Me, too")
                rt.POP_WITH()
            else:
                rt.SET_NAME('THIS.PushButton2.Text', "Click Me, too")
                rt.SET_NAME('Sender.Text', "Click Me")
                rt.SET_NAME('Sender.Font.bold', False)
                rt.SET_NAME('Sender.Font.Size', 11)
        
        def pushbutton1_onclick_2(self, sender):
            this = self
            rt.WRITE("clicked button A: handler 2")
        
        def pushbutton1_onclick_3(self, sender):
            this = self
            rt.WRITE("clicked button A: handler 3")
        
        def pushbutton1_onmouserbutton(self, sender):
            this = self
            rt.WRITE("right click")
        
        def pushbutton1_onmousemove(self, sender):
            this = self
            rt.WRITE(["over button: 1 " ])
        
        def pushbutton2_onclick(self, sender):
            this = self
            rt.WRITE("clicked button 2")
            rt.WRITE(rt.GET(sender, ['Text']))
            if rt.TRUE(rt.BINOP(rt.PRIMARY('THIS.PushButton2.Text'), '==', "Click Me, too")):
                rt.SET_NAME('THIS.PushButton1.Text', "Click Me")
                rt.SET_NAME('Sender.Text', "Click Me")
            else:
                rt.SET_NAME('THIS.PushButton1.Text', "Click Me")
                rt.SET_NAME('Sender.Text', "Click Me, too")
"""

if __name__ == '__main__':
    EntryPoint(main())
