// ----------------------------------------------------------------------------
// @file    rcs_Spanish.pas
// @author  Jens Kallup - paule32.jk@gmail.com
//
// @copy    IBE-Software - (c) 2022 HelpNDoc 8.1
//          all rights reserved.
//
// @desc    This Pascal script contains the locales strings for Spanish users.
// ---------------------------------------------------------------------------

const RCS_EFile                  = 'fichero';
const RCS_EFileDoesNotExists     = 'no existe';
const RCS_EError                 = 'error';
const RCS_EErrorInScript         = 'errores incluidos en este script';
const RCS_EErrorNoIniFile        = 'no se ha podido encontrar el archivo de configuración';
const RCS_EErrorNoHandleToParser = 'no hay clase de mango para el analizador sintáctico';
const RCS_EErrorOutOfBounds      = 'fuera de los límites';
const RCS_EErrorListIndex        = 'índice de la lista fuera de los límites';
const RCS_EErrorStringListDuplicates = 'la lista de cadenas contiene duplicados';
const RCS_EErrorCircularAssign   = 'asignación de puntero circular a puntero';
const RCS_EErrorOccur            = 'se produce una excepción';
const RCS_EErrorDivByZero        = 'dividir por cero';
const RCS_EErrorParser           = 'error de sintaxis';
const RCS_EErrorUnexpectedChar   = 'carácter inesperado encontrado';
