// ----------------------------------------------------------------------------
// @file    rcs_German.pas
// @author  Jens Kallup - paule32.jk@gmail.com
//
// @copy    IBE-Software - (c) 2022 HelpNDoc 8.1
//          all rights reserved.
//
// @desc    This Pascal script contains the locales strings for German users.
// ---------------------------------------------------------------------------

const RCS_EFile                  = 'Datei';
const RCS_EFileDoesNotExists     = 'existiert nicht';
const RCS_EError                 = 'Fehler';
const RCS_EErrorInScript         = 'Das Script enthält Fehler';
const RCS_EErrorNoIniFile        = 'Die Konfigurations-Datei konnte enicht gefunden werden';
const RCS_EErrorNoHandleToParser = 'kein Verweis auf Parser-Klasse => nil';
const RCS_EErrorOutOfBounds      = 'Listenindex unter- oder überschritten';
const RCS_EErrorListIndex        = 'Listenindex überschritten';
const RCS_EErrorStringListDuplicates = 'String-Liste enthält Duplikate';
const RCS_EErrorCircularAssign   = 'zirkularer Zeiger auf Zeiger';
const RCS_EErrorOccur            = 'Ausnahmefehler geliefert';
const RCS_EErrorDivByZero        = 'Division durch null';
const RCS_EErrorParser           = 'Syntax-Fehler';
const RCS_EErrorUnexpectedChar   = 'unerwartetes Zeichen gefunden';
