// ----------------------------------------------------------------------------
// @file    rcs_French.pas
// @author  Jens Kallup - paule32.jk@gmail.com
//
// @copy    IBE-Software - (c) 2022 HelpNDoc 8.1
//          all rights reserved.
//
// @desc    This Pascal script contains the locales strings for French users.
// ---------------------------------------------------------------------------

const RCS_EFile                  = 'fichier';
const RCS_EFileDoesNotExists     = 'n''existe pas';
const RCS_EError                 = 'erreur';
const RCS_EErrorInScript         = 'erreurs incluses dans ce script';
const RCS_EErrorNoIniFile        = 'le fichier de paramètres n''a pas pu être trouvé';
const RCS_EErrorNoHandleToParser = 'pas d''identifiant de classe pour l''analyseur';
const RCS_EErrorOutOfBounds      = 'hors limites';
const RCS_EErrorListIndex        = 'index de liste hors limites';
const RCS_EErrorStringListDuplicates = 'la liste de chaînes contient des doublons';
const RCS_EErrorCircularAssign   = 'affectation circulaire de pointeur à pointeur';
const RCS_EErrorOccur            = 'l exception se produit';
const RCS_EErrorDivByZero        = 'diviser par zéro';
const RCS_EErrorParser           = 'erreur de syntaxe';
const RCS_EErrorUnexpectedChar   = 'caractère inatt caractère trouvé';
