// ----------------------------------------------------------------------------
// @file    rcs_English.pas
// @author  Jens Kallup - paule32.jk@gmail.com
//
// @copy    IBE-Software - (c) 2022 HelpNDoc 8.1
//          all rights reserved.
//
// @desc    This Pascal script contains the locales strings for English users.
// ----------------------------------------------------------------------------

const RCS_EFile                  = 'file';
const RCS_EFileDoesNotExists     = 'does not exists';
const RCS_EError                 = 'error';
const RCS_EErrorInScript         = 'errors included in this script';
const RCS_EErrorNoIniFile        = 'the settings file could not be found';
const RCS_EErrorNoHandleToParser = 'no class handle to parser => nil';
const RCS_EErrorOutOfBounds      = 'out of bounds';
const RCS_EErrorListIndex        = 'list index out of bounds';
const RCS_EErrorStringListDuplicates = 'string list contains duplicates';
const RCS_EErrorCircularAssign   = 'circular pointer to pointer assignment';
const RCS_EErrorOccur            = 'exception occur';
const RCS_EErrorDivByZero        = 'divide by zero';
const RCS_EErrorParser           = 'syntax error';
const RCS_EErrorUnexpectedChar   = 'unexpected character found';
